buildscript {
    repositories {
        mavenCentral()
        maven { url = "https://repo.spring.io/release" }
    }
}

plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${dependencyManagementVersion}"
    id 'com.vaadin' version "${vaadinVersion}"
}

group = 'com.vertex'
version = '1.0.0'
description = 'oauth ui'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    maven {
        name = "nexus"
        url = uri("http://localhost:7900/repository/maven-releases/")
        allowInsecureProtocol = true

        credentials {
            username = project.findProperty("nexus_username") ?: "admin"
            password = project.findProperty("nexus_password") ?: "admin"
        }
    }
    mavenCentral()
    maven { setUrl("https://maven.vaadin.com/vaadin-addons") }
}

configurations {
    developmentOnly
    runtimeClasspath {
        extendsFrom developmentOnly
    }
}

dependencies {
    implementation 'com.vertex:core:' + coreVersion
    implementation 'com.vertex:frontend-core:' + frontendCoreVersion
    implementation('com.vaadin:vaadin-spring-boot-starter')
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    developmentOnly('org.springframework.boot:spring-boot-devtools', 'com.vaadin:vaadin-dev')
    testImplementation('org.springframework.boot:spring-boot-starter-test')
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:$springCloudVersion"
        mavenBom "com.vaadin:vaadin-bom:$vaadinVersion"
    }
}
