plugins {
    id 'java-library'
    id 'maven-publish'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${dependencyManagementVersion}"
}

group = 'com.vertex'
version = '1.0.0'
description = 'backend-core'

bootJar {
    enabled = false
}

jar {
    enabled = true
    archiveClassifier.set('')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    maven {
        name = "nexus"
        url = uri("http://localhost:7900/repository/maven-releases/")
        allowInsecureProtocol = true

        credentials {
            username = project.findProperty("nexus_username") ?: "admin"
            password = project.findProperty("nexus_password") ?: "admin"
        }
    }
    mavenCentral()
}

dependencies {
    api platform("org.springframework.boot:spring-boot-dependencies:${springBootVersion}")
    api platform("org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}")

    implementation "org.mapstruct:mapstruct:${mapStructVersion}"
    implementation "com.vertex:core:${coreVersion}"

    api 'org.springframework.boot:spring-boot-starter-actuator'
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.cloud:spring-cloud-starter-config'
    api 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    api 'org.springframework.cloud:spring-cloud-starter-openfeign'
    api 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'
    api 'org.springframework.boot:spring-boot-starter-aop'
    api 'org.springframework.boot:spring-boot-starter-data-jpa'
    api 'org.springframework.boot:spring-boot-starter-security'
    api 'org.springframework.security:spring-security-acl'
    api "com.github.ulisesbocchio:jasypt-spring-boot-starter:${jasyptVersion}"
    api "nl.basjes.parse.useragent:yauaa:${userAgentVersion}"
    api "io.jsonwebtoken:jjwt-api:${jwtVersion}"
    api('com.redis.om:redis-om-spring:' + redisOmVersion) {
        exclude group: 'com.microsoft.onnxruntime', module: 'onnxruntime'
    }
    api "org.springdoc:springdoc-openapi-starter-webmvc-ui:${openApiVersion}"

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapStructVersion}"
    annotationProcessor('com.redis.om:redis-om-spring:' + redisOmVersion) {
        exclude group: 'com.microsoft.onnxruntime', module: 'onnxruntime'
    }
    runtimeOnly "io.jsonwebtoken:jjwt-impl:${jwtVersion}"
    runtimeOnly "io.jsonwebtoken:jjwt-jackson:${jwtVersion}"
    //*DEFAULT*
    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    //*DEFAULT*
}

tasks.named('test') {
    useJUnitPlatform()
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
        }
    }
    repositories {
        maven {
            name = "nexus"
            url = uri("http://localhost:7900/repository/maven-releases/")
            allowInsecureProtocol = true

            credentials {
                username = project.findProperty("nexus_username") ?: "admin"
                password = project.findProperty("nexus_password") ?: "admin"
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs.addAll([
            '-parameters',
            '-Amapstruct.suppressGeneratorTimestamp=true',
            '-Amapstruct.defaultComponentModel=spring'
    ])
}
