spring:
  application:
    name: CONFIG-SERVER
  profiles:
    active:
      - native
  cloud:
    config:
      name: vertex
      server:
        native:
          search-locations:
            - ENC(trK06WjYBgVn/GJf656xL+NhLb0tLOWobVooyI9l3CBgHNJz1K6Nah0+aXCIBFMlGxmZE7CNiJYE0E400lyg5qArHHoPQswKNfchLhTofcM=)

server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7801/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, refresh