spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: ENC(UP5obuLAwrp8RUjA3MuRIket/VKudSu2QbB/icM+Ed1Rgm6uxNxxSkbMxSwvhWdIlbYl7OZw4EgNRYcNvAj59JZ9e0xRR292YcmzHyBJWRw=)
          username: mohammad-ali-asheghi
          password: ENC(Hhn69rINe79VDvDualHnd6DRtSdghrz7KbzGCSxIk0z4KObQwXVaM7k2RjUb1Re1FWrJNuI9d6FjeN7t2bquKcNogpwg62KV8fEXW2oaUTSd85230WysIg/4V+qeJGrmgZP5zM6a7Oq6nf+EbpfTPanWJna5Be1M5fXROg6UdFA=)
          force-pull: true
          clone-on-start: true
          default-label: main
          search-paths: ENC(TzY5DmyefzG47h4AVcp0pxNYTBrWOCF00LSvgxmJgDUEml3RSKjQVHGRAyljUEGc)

server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7801/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, refresh